### ISSUE TITLE
Using the Expanded Storage feature of Unlock+ hides the inventory slots of a coop

### ISSUE THREAD

**Issue by Thraxerrrr** [Thraxerrrr/RavencrestCouriers#3]
There should be a 3x5 inventory grid, but it disappears, rendering the coop nonfunctional:

![coop-inventory](https://user-images.githubusercontent.com/64758176/99077134-92171e00-25bc-11eb-87cd-0a778fd2bd88.png)

**Comment by AndroidSalmon** [comment]
Hello thraxerrrr! Thanks for your issue report.

For future reports, please use the format seen in #1. This ensures our top quality developer can better understand what the issue is and how to possibly resolve it.

**Comment by Thraxerrrr** [comment]
XD
Fine!
